Accounting:
  children:
    db_servers:
      hosts:
        DB:
          ansible_host: 3.129.191.209
    lb_servers:
      hosts:
        LB:
          ansible_host: 3.13.1.226
    web_servers:
      hosts:
        WEB:
          ansible_host: 3.21.200.89
  vars:
    ansible_ssh_private_key_file: ../app_key.pem
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    ansible_user: ubuntu
    app_name: Test
    db_port: 27017
    db_servers:
    - 192.168.0.13
    lb_port: 80
    web_server_port: 8080
    web_servers:
    - 192.168.0.12
